services:
  ff-iii-toolkit-api:
    image: wini35337/ff-iii-toolkit-api:latest
    container_name: ff-iii-toolkit-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - default

  firefly-proxy:          # ← MUSI być wewnątrz "services:"
    image: nginx:latest
    container_name: firefly-proxy
    depends_on:
      - ff-iii-toolkit-api
    volumes:
      - ./nginx-firefly.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default

networks:
  default:
    driver: bridge
